# Generated by Django 4.1 on 2022-10-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="upload/image")),
                ("product_name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
